//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JaBak.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class produit
    {
        public int id_produit { get; set; }
        public string libelle { get; set; }
        public string catégorie { get; set; }
        public Nullable<double> prix { get; set; }
        public Nullable<int> quantité { get; set; }
        public string id_fournisseur { get; set; }
        public byte[] PhotoFile { get; set; }
        public string ImageMimeType { get; set; }
    }
}
